---
title: "Viz 2"
output: github_document
date: "2024-10-01"
---

```{r setup, include = FALSE}
library(tidyverse)
```

Import the weather data
```{r, message=FALSE}
weather_df <- 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Make a fancy scatterplot: add labels
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(title = "Temperature scatterplot",
       x = "Minimum temp (C)",
       y = "Maximum temp (C)",
       color = "Location",
       caption = "Weather data taken from rnoaa package for 3 stations.")
```

Scales -- start with `x` and `y` and then do `color`
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(title = "Temperature scatterplot",
       x = "Minimum temp (C)",
       y = "Maximum temp (C)",
       color = "Location",
       caption = "Weather data taken from rnoaa package for 3 stations.") + 
  scale_x_continuous(breaks = c(-15,0,20),
                     labels = c("-15C","0C","20C")) + 
  scale_y_continuous(limits = c(0,30),
                     transform = "sqrt") 
```

Look at color

```{r}
ggp_scatterplot <- weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(title = "Temperature scatterplot",
       x = "Minimum temp (C)",
       y = "Maximum temp (C)",
       color = "Location",
       caption = "Weather data taken from rnoaa package for 3 stations.") +
  viridis::scale_color_viridis(discrete = TRUE) 
```

## Themes

```{r}
ggp_scatterplot + 
  theme_bw() +
  theme(legend.position = "bottom")
```

Order matters here
```{r}
ggp_scatterplot + 
  theme(legend.position = "bottom") +
  theme_bw() 
```

some other themes
```{r}
ggp_scatterplot + 
  theme(legend.position = "bottom") +
  theme_minimal() 
```

```{r}
ggp_scatterplot + 
  theme(legend.position = "bottom") +
  theme_classic() 
```

```{r}
ggp_scatterplot + 
  theme(legend.position = "bottom") +
  ggthemes::theme_economist() 
```